### ISSUE TITLE
Oibek

### ISSUE THREAD

**Issue by khumouz** [PacViewer/alias#1]
### 📡 Network

Mainnet

### 🔍 Addresses

```markdown
- account:pc1zqwxy327vlffvhw9yqr87wwa2pstl3av3g24c7k
- validator:pc1phk60cgxl90xf54hne9eejwt6ex8wkakuywhy7f
- account:pc1z8sf87ykve5rgcqra5dzgtw5slx72ewv7kwvrpn
- validator:pc1pwh4lh0t7y9l0p8fa6h9yrlnw7dpld8zr5kefwd
```

### 📌 Service name

oibek

### ✉️ Email

oybek.khaydar@gmail.com

### 📝 Description

I love **PAC**

**Comment by ja7ad** [comment]
@khumouz Please send your request to https://forms.gle/MeBxib3EfhJ5zMdAA
