### ISSUE TITLE
[Molla202]

### ISSUE THREAD

**Issue by molla202** [PacViewer/alias#2]
### 📡 Network

Mainnet

### 🔍 Addresses

```markdown
- account:[pc1zcnwax7mc30tzra2k34ts7c0kgg22gmz50xacmy]
- validator:[pc1pywlzu7a6aptz88fl4zh57hf6cykaqqgvmke9fq]
- account:[pc1z6y66j6dln3cpr3jaqetx5jh869rg98ppc6wfgw]
- validator:[pc1phjsph6h5xvezsnpxlf4uj5pz346rz326qk0v0t]
```

### 📌 Service name

molla202

### 🌐 Website

https://github.com/molla202

### ✉️ Email

molla202@gmail.com

### 🌄 Icon

https://github.com/molla202/molla202/blob/main/2005-02-02_012323_g2_05_msxlabs.com.png?raw=true

### 📝 Description

Professional validator.

**Comment by molla202** [comment]
waiting

**Comment by ja7ad** [comment]
@molla202 Please send your request to https://forms.gle/MeBxib3EfhJ5zMdAA
