### ISSUE TITLE
Cmdexe

### ISSUE THREAD

**Issue by Xelp66** [PacViewer/alias#3]
### 📡 Network

Mainnet

### 🔍 Addresses

```markdown
- account:pc1z7wegpdqqe0rfd8s35auk962yg3djyvgw5emesd
- validator:pc1p28m7k2j9sm48u7qn99pzmuw0zclpcwj38yqnq9
```

### 📌 Service name

Cmdexe-Solo

### 🌐 Website

NaN

### ✉️ Email

github/Xelp66

### 🌄 Icon

https://imgur.com/a/iHA9kuy

### 📝 Description

from beginning i am here. Thanks for great job team !!

**Comment by ja7ad** [comment]
@Xelp66 Please send your request to https://forms.gle/MeBxib3EfhJ5zMdAA
