### ISSUE TITLE
Request alias name for Node39.TOP

### ISSUE THREAD

**Issue by Node39TOP** [PacViewer/alias#5]
### 📡 Network

Mainnet

### 🔍 Addresses

```markdown
- validator: pc1pvlhl4utaqxjy3t2kheqf32ja0w6xhg669tfy6n
```

### 📌 Service name

Node39.TOP

### 🌐 Website

https://node39.top

### ✉️ Email

contact@node39.top

### 🌄 Icon

https://node39.top/logo/icon32x32.png

### 📝 Description

POS Node & Validator

**Comment by ja7ad** [comment]
@Node39TOP Please send your request to https://forms.gle/MeBxib3EfhJ5zMdAA
