### ISSUE TITLE
TriNguyen279

### ISSUE THREAD

**Issue by TriNguyen79** [PacViewer/alias#6]
### 📡 Network

Mainnet

### 🔍 Addresses

```markdown
- account:pc1zj7jecacv09z0yh274cvkyn6w6hrpx2wez8j3f3
- validator:pc1plqvrzgpgmg27rumv7uuven3jd6yjqwtjqapf2k
```

### 📌 Service name

TriNguyen279

### ✉️ Email

andongnhi79@gmail.com

**Comment by ja7ad** [comment]
@TriNguyen79 Please send your request to https://forms.gle/MeBxib3EfhJ5zMdAA
