### ISSUE TITLE
Request alias name for [node89]

### ISSUE THREAD

**Issue by luudst** [PacViewer/alias#7]
### 📡 Network

Mainnet

### 🔍 Addresses

```markdown
- account:[pc1zkzhu96y5mdvl3nqyt5le2rvzrddmzxcglp6dfm]
- validator:[pc1p7pzxnwqx8w5c3kafhjzq9q69pm0c8x4rgdgyh3]
- account:[pc1zkzhu96y5mdvl3nqyt5le2rvzrddmzxcglp6dfm]
```

### 📌 Service name

node89

### 🌐 Website

https://x.com/noname90884289

### ✉️ Email

luups2018@gmail.com

### 🌄 Icon

https://github.com/luudst/Chainbase/blob/main/logo.png

**Comment by ja7ad** [comment]
@luudst Please send your request to https://forms.gle/MeBxib3EfhJ5zMdAA
